### ISSUE TITLE
Consistent versioning numbers across apps

### ISSUE THREAD

**Issue by ChristopherA** [BlockchainCommons/iOS-GordianGuardian#25]
See: https://github.com/BlockchainCommons/Community/blob/master/release-path.md

Not sure correct answer, we should discuss with Shannon, but it certainly shouldn't be `1.0 (8)` as it currently is. Gordian Cosigner is 0.1.13 as it isn't even beta yet as features are not frozen yet.

/cc @shannona

**Comment by shannona** [comment]
We have two standards that we're laying out for versioning: words and semantic numbering.

Here's our development phases:
https://github.com/BlockchainCommons/Community/blob/master/release-path.md

Here's our semantic numbering:
https://github.com/BlockchainCommons/wips#wip-version

Here's an issue: we haven't actually put these together. The semantic numbers were in relation to the WIPs, so we said that 1.0.0 was fully drafted, 2.0.0 was backward-incompatible changes, etc. The release path was primarily for our repos, though it's intended to address our WIPs too.

How do we combine these? is 1.0.0 the same as Alpha? Beta? Feature Complete? Final?

How do we incorporate release candidates? (I assume Guardian is actually 1.0 rc8.

If we get answers for those, I can merge the semantic versioning descriptions into the release path document, and then we'll have a foundation for numbering of this sort.

**Comment by wolfmcnally** [comment]
Here is the problem with version numbers: semantic versioning is great for developers using libraries, because they can easily see the difference between bugfix releases (last place), enhancements with no breaking changes (middle place) or breaking API changes (first place). This is in tension with version numbers used for public-facing releases, which are essentially marketing tools. For a library, even a small breaking change should warrant an increment of the first-place number. For a released app, breaking changes of this sort should *never* happen, so when should you increment the first number? The answer is, whenever you do a release that has enough features to warrant it.

So the semantics of public-facing version numbers are different from semver as used by developers. Apple, for instance, will not allow the release of any app into the App Store that is tagged with a version number less than 1.0 or has a pre-release tag like "beta" or "b" associated with it. That is why for Guardian I have given it the public-facing release number of "1.0.0 (#)" where (#) is the build number. Basically *every* pre-release version of an app should be 1.0 (something). Once it actually is released, it's just 1.0. After that you can do bug fix released by adding a third place, moderate upgrades by incrementing the second place, and major upgrades by incrementing the first. As I mentioned, all versions of public-facing apps should never break backwards compatibility, and this is a *different* definition of the meaning of the first place than in semver.

**Comment by wolfmcnally** [comment]
On the other hand my Swift LifeHash library is at version 6. Why? Because I have done six releases that have breaking changes. In the case of Swift Package Manager, if you tell it to start using the latest version of a library, and that version is currently 2.0.0, it will when you ask it to update that package to 2.0.1 or 2.2.4 if those are the then most-recent, but it will never, without being specifically told, upgrade it to 3.x.x, because that is assumed to include breaking API changes, however minor.

**Comment by wolfmcnally** [comment]
The difference is that Guardian is user-facing, for release through the App Store, and LifeHash is developer-facing. So the semantics of their version numbers is *different*. BC projects all need to take this difference into account.

**Comment by wolfmcnally** [comment]
I should also mention that iOS App Store releases are tagged with a string version number, which is usually something like "1.0", and an integer build number, which is usually monotonically increasing for each release. So currently Guardian is at 1.0 (8). You can see this number in Test Flight. But you cannot see it in the App Store. Even after release, Apple uses the build number as the "actual" version it uses to keep track of the various builds you upload. The version number string is strictly user-facing, and except for the requirement that it not include "beta" or some such, it's up to the developer how to use it.

**Comment by wolfmcnally** [comment]
Terms like "alpha" and "beta" are useful to describe development phases, but generally aren't useful in version numbers.

**Comment by ChristopherA** [comment]
Then as GG is really being prepared for public TestFlight, not App Store, should it not be something like 0.1 first? Or 0.9 until we have a freeze for App Store review?

**Comment by ChristopherA** [comment]
I wonder if we should have an app version convention that 0.5 is first believed to be feature complete and increase from there until 1.0 App Store candidate?

**Comment by wolfmcnally** [comment]
> I wonder if we should have an app version convention that 0.5 is first believed to be feature complete and increase from there until 1.0 App Store candidate?

We might be able to do that in the future, but it's not clear to me the App Store will under any circumstances allow going 'backwards' from a build number of 8 to a build number of 0.5.0.

I know one thing for sure: The system I use works and works well with Apple, and avoids all sorts of trouble.

- [Technical Note TN2420: Version Numbers and Build Numbers](https://developer.apple.com/library/archive/technotes/tn2420/_index.html)
- [CFBundleVersion](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-102364)
- [CFBundleShortVersionString](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/20001431-111349)
- [Forum: Version Number](https://developer.apple.com/forums/thread/50931)
- [Forum: Why Apple Rejects My Version Number](https://developer.apple.com/forums/thread/109765)

**Comment by shannona** [comment]
On Tue, Feb 9, 2021 at 12:42 PM Wolf McNally <notifications@github.com>
wrote:

> We might be able to do that in the future, but it's not clear to me the
> App Store will under any circumstances allow going 'backwards' from a build
> number of 8 to a build number of 0.5.0.
>
>
Last time I was building apps, which is a few years back now, it definitely
wouldn't. But, I think we're looking for future clarity.

Shannon

**Comment by wolfmcnally** [comment]
Well, the rules are also different between iOS and Mac. On Mac, the Build number *must* be monotonically increasing integer. On iOS it has to be increasing, but doesn't need to be an integer. The method I use works reliably for both.
